# Site settings
title: OpenSatMap
email: opensatmap@gmail.com
description: "OpenSatMap: A Fine-grained High-resolution Satellite Dataset for Large-scale Map Construction"
baseurl: ""
url: "https://opensatmap.github.io/"
twitter_username: opensatmap
github_username:  opensatmap
theme: jekyll-theme-hacker

# Build settings
markdown: kramdown
permalink: pretty
